# Generated by Django 3.2.9 on 2021-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='counter_value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
